final products = [
  {
    'id': '0',
    'title': 'Settlers of Catan',
    'category': 'Strategy',
    'players': '3-4',
    'duration': '60-120 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '1',
    'title': 'Ticket to Ride',
    'category': 'Family',
    'players': '2-5',
    'duration': '30-60 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '2',
    'title': 'Codenames',
    'category': 'Party',
    'players': '4-8+',
    'duration': '15-30 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '3',
    'title': 'Pandemic',
    'category': 'Cooperative',
    'players': '2-4',
    'duration': '45 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '4',
    'title': 'Azul',
    'category': 'Abstract',
    'players': '2-4',
    'duration': '30-45 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '5',
    'title': 'Terraforming Mars',
    'category': 'Strategy',
    'players': '1-5',
    'duration': '120 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '6',
    'title': 'Sea Salt and Pepper',
    'category': 'Family',
    'players': '3-4',
    'duration': '60-120 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '7',
    'title': 'Dixit',
    'category': 'Party',
    'players': '3-6',
    'duration': '30 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '8',
    'title': 'Forbidden Island',
    'category': 'Cooperative',
    'players': '2-4',
    'duration': '30 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '9',
    'title': 'Santorini',
    'category': 'Abstract',
    'players': '2-4',
    'duration': '20 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '10',
    'title': 'Twilight Struggle',
    'category': 'Strategy',
    'players': '2',
    'duration': '180 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '11',
    'title': 'Carcassonne',
    'category': 'Family',
    'players': '2-5',
    'duration': '30-45 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '12',
    'title': 'Wavelength',
    'category': 'Party',
    'players': '2-12+',
    'duration': '30-45 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '13',
    'title': 'Ghost Stories',
    'category': 'Cooperative',
    'players': '1-4',
    'duration': '60 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '14',
    'title': 'Onitama',
    'category': 'Abstract',
    'players': '2',
    'duration': '15 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '15',
    'title': 'Scythe',
    'category': 'Strategy',
    'players': '1-7',
    'duration': '90-150 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '16',
    'title': 'Splendor',
    'category': 'Family',
    'players': '2-4',
    'duration': '30 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '17',
    'title': 'Just One',
    'category': 'Party',
    'players': '3-7',
    'duration': '20 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '18',
    'title': 'Pandemic Legacy: Season 1',
    'category': 'Cooperative',
    'players': '2-4',
    'duration': '60 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '19',
    'title': 'Quarto',
    'category': 'Abstract',
    'players': '2',
    'duration': '15-30 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '20',
    'title': 'Agricola',
    'category': 'Strategy',
    'players': '1-5',
    'duration': '30-150 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '21',
    'title': 'Kingdomino',
    'category': 'Family',
    'players': '2-4',
    'duration': '15-20 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '22',
    'title': 'Telestrations',
    'category': 'Party',
    'players': '4-8',
    'duration': '30-60 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '23',
    'title': 'Flash Point: Fire Rescue',
    'category': 'Cooperative',
    'players': '1-6',
    'duration': '45 minutes',
    'imageURL': 'assets/images/none.png',
  },
  {
    'id': '24',
    'title': 'Quoridor',
    'category': 'Abstract',
    'players': '2-4',
    'duration': '15-30 minutes',
    'imageURL': 'assets/images/none.png',
  }
];
